### ISSUE TITLE
Terratonic crashes when generating a specific chunk

### ISSUE THREAD

**Issue by phalcon22** [Apollounknowndev/tectonic#183]
### Steps to reproduce:
**Make a fabric server with following configuration**:
_Fabric_: fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar
_Mods_:
-  fabric-api-0.100.4+1.21.jar
- tectonic-fabric-1.21-2.4.0.jar
- Terralith_1.21_v2.5.3.jar

 _Seed_: -5757465302180938436

**Connect to the server and tp to the coords 1175 150 -2233**

**Witness crash**

### LOG

> [16:22:48] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[16:22:48] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[16:22:48] [main/INFO]: Loading 42 mods:
	- fabric-api 0.100.4+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.48+f71b366fd1
	   |-- fabric-command-api-v2 2.2.27+6a6dfa19d1
	   |-- fabric-commands-v0 0.2.65+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.15+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.3.2+78017270d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.9+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8cd1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.11+6573ed8cd1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.23+78017270d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.70+df3654b3d1
	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5+78017270d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.80+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.21
	- tectonic 2.4.0
	- terralith 2.5.3
[16:22:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/I:/Nouveau%20dossier/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[16:22:50] [main/INFO]: Compatibility level set to JAVA_17
[16:22:51] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[16:22:59] [main/WARN]: resource-pack-id missing, using default of 7cb7dbe1-687b-34c3-aa82-899bcaae4118
[16:22:59] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:22:59] [main/INFO]: Found new data pack fabric, loading it automatically
[16:22:59] [main/INFO]: Found new data pack fabric-convention-tags-v2, loading it automatically
[16:22:59] [main/INFO]: Found new data pack terralith, loading it automatically
[16:22:59] [main/INFO]: Found new data pack terratonic, loading it automatically
[16:23:00] [main/INFO]: No existing world data, creating new world
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_snowy as it is missing following references: terralith:reference/temperature/frozen_all (from terralith)
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_taiga as it is missing following references: terralith:reference/taiga (from terralith)
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_desert as it is missing following references: terralith:reference/desert_all (from terralith)
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_savanna as it is missing following references: terralith:reference/savanna (from terralith)
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_jungle as it is missing following references: terralith:reference/jungle (from terralith)
[16:23:01] [Worker-Main-4/ERROR]: Couldn't load tag biome_tag_villagers:villager_swamp as it is missing following references: terralith:reference/swamp (from terralith)
[16:23:01] [main/INFO]: Loaded 1296 recipes
[16:23:01] [main/INFO]: Loaded 1399 advancements
[16:23:02] [main/INFO]: Applied 0 biome modifications to 0 of 158 new biomes in 3.681 ms
[16:23:02] [Server thread/INFO]: Starting minecraft server version 1.21
[16:23:02] [Server thread/INFO]: Loading properties
[16:23:02] [Server thread/INFO]: Default game type: SURVIVAL
[16:23:02] [Server thread/INFO]: Generating keypair
[16:23:02] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:23:02] [Server thread/INFO]: Using default channel type
[16:23:02] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:23:02] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:23:02] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:23:02] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:23:02] [Server thread/INFO]: Preparing level "world"
[16:23:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:23:07] [Worker-Main-1/INFO]: Preparing spawn area: 2%
[16:23:07] [Worker-Main-9/INFO]: Preparing spawn area: 2%
[16:23:08] [Worker-Main-15/INFO]: Preparing spawn area: 2%
[16:23:08] [Worker-Main-11/INFO]: Preparing spawn area: 2%
[16:23:09] [Worker-Main-10/INFO]: Preparing spawn area: 18%
[16:23:09] [Worker-Main-11/INFO]: Preparing spawn area: 18%
[16:23:10] [Worker-Main-8/INFO]: Preparing spawn area: 51%
[16:23:10] [Worker-Main-10/INFO]: Preparing spawn area: 51%
[16:23:11] [Worker-Main-11/INFO]: Preparing spawn area: 51%
[16:23:11] [Server thread/INFO]: Time elapsed: 4357 ms
[16:23:11] [Server thread/INFO]: Done (9.034s)! For help, type "help"
[16:23:28] [Server thread/INFO]: Phalcon22[/192.168.1.254:59520] logged in with entity id 37 at (-5.5, 133.0, 8.5)
[16:23:28] [Server thread/INFO]: Phalcon22 joined the game
[16:23:32] [Server thread/INFO]: [Phalcon22: Set own game mode to Spectator Mode]
[16:23:33] [Server thread/INFO]: [Phalcon22: Teleported Phalcon22 to 1175.500000, 150.000000, -2232.500000]
[16:23:33] [Server thread/WARN]: Phalcon22 moved too quickly! 1181.0,17.0,-2241.0
[16:23:33] [Server thread/WARN]: Phalcon22 moved too quickly! 1181.0,17.0,-2241.0
[16:23:33] [Server thread/WARN]: Phalcon22 moved too quickly! 1181.0,17.0,-2241.0
[16:23:34] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_60445(class_3898.java:647) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18857(class_3215.java:525) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:137) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8402(class_1937.java:208) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8497(class_1937.java:202) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8500(class_1937.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8316(class_1937.java:383) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5692(class_1297.java:3408) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5713(class_1297.java:1448) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5876(class_1297.java:1439) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5670(class_1297.java:516) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:406) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2468) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:312) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:588) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:401) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Requested chunk unavailable during world generation
	at net.minecraft.class_3233.method_8402(class_3233.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_16359(class_4538.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_4543.method_22393(class_4543.java:79) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_23753(class_4538.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_6792.method_38918(class_6792.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_6661.method_14452(class_6661.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_6796.method_39649(class_6796.java:48) ~[server-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:356) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:361) ~[server-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(class_9310.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(class_9770.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60442(class_3898.java:632) ~[server-intermediary.jar:?]
	at net.minecraft.class_9761.method_60461(class_9761.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60428(class_9759.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60427(class_9759.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60432(class_9759.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_9759.method_60424(class_9759.java:59) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_60446(class_3898.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by Apollounknowndev** [comment]
Crash caused by Terralith.
