### ISSUE TITLE
Server won't start with tectonic

### ISSUE THREAD

**Issue by NickeyHab** [Apollounknowndev/tectonic#202]
I would like my server to generate with tectonic but it just gives an error. It will generate without the tectonic. I do run more mods including terralith and geophilic but i feel like those aren't causing the problem.
(sorry I couldn't figure out how to add the crash label)
This is from the crash log:

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.4.jar%2362!/:11.0.4+main.d2e20e43] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.SurfaceSystem.<init>(SurfaceSystem.java:66) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.RandomState.<init>(RandomState.java:44) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.RandomState.create(RandomState.java:33) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.<init>(ChunkMap.java:172) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:88) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:262) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.createLevels(MinecraftServer.java:367) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:337) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:193) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23136!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?] {}
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for tectonic.mixins.json:NoisesMixin from mod tectonic during activity: [Transform -> Method tectonic$fixTectonicNoiseSeeds(Lnet/minecraft/resources/ResourceLocation;)Lnet/minecraft/resources/ResourceLocation; -> INVOKEVIRTUAL -> java/lang/String::equals:(Ljava/lang/Object;)Z]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:187) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	... 25 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: java.lang.String
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:187) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	... 25 more
Caused by: java.lang.ClassNotFoundException: java.lang.String
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:187) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar%2375!/:0.14.0+mixin.0.8.6] {}
	... 25 more

**Comment by Apollounknowndev** [comment]
Very stale issue at this point, but this was likely due to a mismatched Java version with the game's shipped version; I've seen similar issues due to people using Java 22 on some mods.
