### ISSUE TITLE
1.20.4 Crash During Forge Loading

### ISSUE THREAD

**Issue by SynSym** [Apollounknowndev/tectonic#79]
Game crashes during forge loading.
Forge Version: 49.0.19
Minecraft Version: 1.20.4
No other mods.
Modpack constructed using the CurseForge app on a Windows 10 computer.
Generated "latest.txt" log follows:

[08:16:39] [main/INFO]: ModLauncher running: args [--username, YangSyn, --version, forge-49.0.19, --gameDir, G:\Play\CurseForge\Minecraft\Instances\Test, --assetsDir, G:\Play\CurseForge\Minecraft\Install\assets, --assetIndex, 12, --uuid, 495d5cd548134cb1a953b3bac69fefae, --accessToken, **********, --clientId, MTA1NjNmOTItOTE2YS00OTAyLTk4NzAtODQzMWI3NzJiNjBl, --xuid, 2535428286764478, --userType, msa, --versionType, release, --width, 1100, --height, 600, --quickPlayPath, G:\Play\CurseForge\Minecraft\Install\quickPlay\java\1705162594535.json, --launchTarget, forge_client]
[08:16:39] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 17.0.8+7-LTS
[08:16:39] [main/INFO]: ModLauncher 10.1.2 starting: java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0
[08:16:39] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[08:16:39] [main/INFO]: Trying GL version 4.6
[08:16:40] [main/INFO]: Requested GL version 4.6 got version 4.6
[08:16:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=jar:file:///G:/Play/CurseForge/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar!/ Service=ModLauncher Env=CLIENT
[08:16:40] [EarlyDisplay/INFO]: GL info: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
[08:16:40] [main/INFO]: Found mod file tectonic-forge-1.20-v2.2.jar of type MOD with provider {mods folder locator at G:\Play\CurseForge\Minecraft\Instances\Test\mods}
[08:16:40] [main/INFO]: Found mod file forge-1.20.4-49.0.19-client.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@748fe51d
[08:16:40] [main/INFO]: Found mod file forge-1.20.4-49.0.19-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@26a4551a
[08:16:40] [main/INFO]: Found mod file javafmllanguage-1.20.4-49.0.19.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@26a4551a
[08:16:40] [main/INFO]: Found mod file mclanguage-1.20.4-49.0.19.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@26a4551a
[08:16:40] [main/INFO]: Found mod file fmlcore-1.20.4-49.0.19.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@26a4551a
[08:16:40] [main/INFO]: Found mod file lowcodelanguage-1.20.4-49.0.19.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@26a4551a
[08:16:40] [main/INFO]: No dependencies to load found. Skipping!

**Comment by SynSym** [comment]
[2024-01-13-1.log.gz](https://github.com/Apollounknowndev/tectonic/files/13928794/2024-01-13-1.log.gz)
There's also this, which may come in handy.

**Comment by fightmesun** [comment]
I'm having the same issue. 

[16/01/2024 09:26:56 AM] Caused by: java.lang.IllegalArgumentException: The specified resource 'tectonic.mixins.json' was invalid or could not be read
[16/01/2024 09:26:56 AM] 	at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
[16/01/2024 09:26:56 AM] 	at SECURE-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)

And here's a log for it. 
[latest.log](https://github.com/Apollounknowndev/tectonic/files/13953745/latest.log)

**Comment by RN0000** [comment]
Any luck on finding a solution so far? I'm having the same issue...

---

Caused by: java.lang.IllegalArgumentException: The specified resource 'tectonic.mixins.json' was invalid or could not be read
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)

**Comment by Apollounknowndev** [comment]
Fixed in v2.2.1.
